### PR TITLE
noise_threshhold -> noise_threshold

### PR DESCRIPTION
**Pull request by MT-Modder**

### CODE REVIEW

**Comment by VanessaE** [comment]
Looks like this one needs a rebase now.

**Comment by MT-Modder** [comment]
Okay I think I did that right.

**Comment by VanessaE** [comment]
Seems right, you just need to squash your commits.

**Comment by MT-Modder** [comment]
Is that possible through the web browser? Haven't messed with git in a while. Nor have I ever squashed commits.

**Comment by VanessaE** [comment]
I don't think so, but from the command line it's easy.  `cd` to the technic directory, `git rebase` first.  Check `git log` and see if the "merge commit" is gone, and `git push -f` if so.  If not, well, I'm never entirely sure of the right procedure.

**Comment by MT-Modder** [comment]
Alright I'll give it a shot, thanks.

**Comment by kaeza** [comment]
News on this?

**Comment by kaeza** [comment]
Rebased and merged at https://github.com/minetest-technic/technic/commit/b67bca1277ee9abcce590d57830617065539372c.

Thanks!

**Pull request closed without merging**
