### PR TITLE
Radiation changes

### PR DESCRIPTION
**Pull request by ShadowNinja**
Changes:
  * Switch reactor to a lead shield (SS was just used as a placeholder since lead wasn't available at the them).  Old reactors converted.
  * Adjust radioactivity math.  This removes the 1000 and 0.25 multipliers, making the math a bit simpler.  It also makes radiation resistance more effective (a large part of the protection from extra layers was just the extra distance).
  * Split radiation code from nuclear reactor.  Radiation isn't necessarily tied to the reactor.
  * Add longer-term radiation damage.  I reduced radioactivity of various things to account for the increased damage.

### CODE REVIEW

**Comment by MT-Modder** [comment]
:+1: Nice!

**Comment by MT-Modder** [comment]
So was this reverted or something?

**Comment by ShadowNinja** [comment]
Erm, it looks like someone removed them with a force-push.

**Comment by ShadowNinja** [comment]
Re-pushed.

**Comment by MT-Modder** [comment]
Sweet!

**Pull request merged**
