### PR TITLE
handling exceptions when quarry digs (eg. when player is nil)

### PR DESCRIPTION
**Pull request by petermaloney**
issues 172, 231, for example with item bones:bones

(sorry I have no idea how to tell github it's issue 172 or 231 again)

This should handle the general case, as an exception handler rather than as a "bug fix" (since the bug is in the other code that assumes player is not nil)

### CODE REVIEW

**Comment by petermaloney** [comment]
actually I'm not sure what happens with the "can_dig = false" lines in the function... (unlike in every other language I used with try/catch). I don't think they have any effect any more, going out of scope before they are used later, but didn't notice anything in testing. What should they do? It doesn't get stuck trying to dig air, and doesn't trigger the exception code for non-diggable things I know (like chests with things in it)... so I don't really know what it does.

**Comment by asl97** [comment]
:-1: this isn't really the way to do it, i suggest making an issue at https://github.com/minetest/minetest_game since the api has specify that player is optional. 
related: #172 #231

**Comment by petermaloney** [comment]
So I did some testing, and I think actually this anonymous function does change the can_dig, so it works fine.

And how is handling exceptions not one option of a right way to do it? It doesn't fix the root cause, but that's the whole point of "exceptions". This is making the code fail gracefully instead of crashing the whole server. And unlike my previous quick fix, this one handles the general case in this one block of code. (are there others we should handle too?)

There are plenty of people out there that think bones works fine, and then when they add the quary, and see a crash, they immediately blame technic and not bones. This will handle it better than blame shifting will. We blame them; they blame you; nothing gets done... right?

**Comment by asl97** [comment]
downstream shouldn't have to suffer just cause upstream doesn't know or want to fix the bug due to not following the api.

what if other mod also use on_dig on the bones?  it would crash.  should every single mod use exception just cause of it and slow down everything, making a messy nested code?

I don't think so.  upstream should fix it and it is just a simple pull request or issue to let the people upstream know about it.

the fix is just a simple one liner `if not player then return end` to add in the bones mod instead of this messy nested stuff.

i didn't make the issue or pull request cause i wasn't the one who gotten the error.

**Comment by t4im** [comment]
The api defines this only after minetest/minetest#2108 which was created due to exactly this kind of confusion. Many mods, including the upstream ones, might simply not have catched up with the decision yet, but should be fixed no matter of a workaround here or elsewhere. Opening up a upstream bugreport would be the sensible thing to do either way.

**Comment by Ekdohibs** [comment]
Closing, as there are problems with rebasing and this should anyway be fixed by https://github.com/minetest/minetest_game/pull/875

**Pull request closed without merging**
