### PR TITLE
Make blast-resistant concrete blast resistant

### PR DESCRIPTION
**Pull request by MT-Modder**
Helps with #246
~~I'll be checking https://github.com/tenplus1/mobs for on_blast checks.~~

Mobs PR: https://github.com/tenplus1/mobs/pull/47 Merged!

### CODE REVIEW

**Comment by ShadowNinja** [comment]
This should check the intensity, so that more intense explosions will destroy it.

**Comment by MT-Modder** [comment]
A blast of tnt uses an intensity of 1:
https://github.com/minetest/minetest_game/blob/master/mods/tnt/init.lua#L96

Does this look good?
```
on_blast = function(pos, intensity)
    if intensity > 1 then
        minetest.remove_node(pos)
    end
end,
```

**Comment by ShadowNinja** [comment]
According to `lua_api.txt` 1 is mid range of regular TNT (although it isn't actually calculated by the mod yet).  I think it should be a bit more resistant than that.  Perhaps 1.5 or so.  Other than that, yes, that looks good.

**Comment by MT-Modder** [comment]
Okay.

It's probably safe to just use the nodename itself instead of fetching it from ```minetest.get_node(pos).name``` since it's within the nodedef, right?

**Comment by ShadowNinja** [comment]
Yes.  You should return the item instead of dropping it though -- as soon as the docs API gets updated to support that.
I'll merge this soon.

**Comment by ShadowNinja** [comment]
0c144cd75c638f1f1c67ae91973f3ff8ffc781dd

**Comment by MT-Modder** [comment]
Okay thanks I'll submit a PR for that once https://github.com/minetest/minetest_game/pull/862 is merged.

It should look like this right?
```
on_blast = function(pos, intensity)
    if intensity > 1 then
        minetest.remove_node(pos)
        return ItemStack("technic:blast_resistant_concrete")
    end
end,
```

**Comment by sofar** [comment]
check the doors mod for how to do this:

e.g. ```return { "technic:blast_resistant_concrete" }```

**Comment by MT-Modder** [comment]
Ah thank you very much. Pretty simple. I'll submit the PR now since it's already supported. I hadn't realized.

**Comment by MT-Modder** [comment]
After this https://github.com/minetest/minetest_game/pull/862 PR the blast intensity next to TNT is about 9 and the intensity at the edge of the blast is about 1. We should probably adjust the check for intensity otherwise it isn't really blast-resistant.

After it's merged of course.

**Pull request closed without merging**
