### PR TITLE
test if stairsplus is available

### PR DESCRIPTION
**Pull request by HybridDog**
approximately the same
https://github.com/Splizard/minetest-mod-snow/pull/8

### CODE REVIEW

**Comment by t4im** [comment]
:+1: 
also great example for why minetest/minetest#1862 could be useful too ;-)

**Comment by ShadowNinja** [comment]
If `extranodes` depends on `stairsplus` it shouldn't just silently fail if it isn't available.  It should either use a hard dependency or it should throw an error.

**Comment by HybridDog** [comment]
>It should either use a hard dependency

how? stairsplus isn't a mod

> it should throw an error

ok

**Comment by ShadowNinja** [comment]
@HybridDog It's a part of moreblocks.  The error would be a `error()`, meaning it would cause the startup to fail and it would print the error.  That way you can see that there's something wrong and fix it.  Loging to infostream is unacceptable, that's only ever enabled when debuging because so many things are logged there.

**Comment by HybridDog** [comment]
>It's a part of moreblocks.

sorry, l thought moreblocks would offer a setting to disable stairsplus…

**Pull request closed without merging**
