### PR TITLE
Add bower.json

### PR DESCRIPTION
**Pull request by diogo-gomes**
Add file bower.json to manage the dependencies of technic mod when installed with [bower](http://bower.io/).

### CODE REVIEW

**Comment by ShadowNinja** [comment]
The file is indented with spaces instead of tabs, and the indentation is messed up near the end of the file.
Does it actually make sense to use bower for this?  I haven't seen any other mods with bower set up.

**Comment by diogo-gomes** [comment]
Indentation updated.

See this project: https://minetest-bower.herokuapp.com/

I think it's make sense use bower, with local bower.json, it's easy and fast configure all mods (single games and servers) with a few commands.

**Comment by Ekdohibs** [comment]
Maybe it would make sense to remove RBA's email address from there as well, since there will to no answer to emails sent to this address.

**Comment by diogo-gomes** [comment]
You can make all necessary modifications.

I only propose the bower.json to manage dependencies (when someone install technic with bower, the mods moreblocks and pipeworks are auto installed). Other info inside the json file is with you.

**Comment by VanessaE** [comment]
No response from the author in ages, closing...

**Pull request closed without merging**
