### PR TITLE
made lasers 10x more precise

### PR DESCRIPTION
**Pull request by petermaloney**

### CODE REVIEW

**Comment by asl97** [comment]
wouldn't this make it 10x heavier?

maybe undoing the removal of the "antialiasing" by https://github.com/minetest-technic/technic/pull/159 would be better than this.

related:
https://github.com/minetest-technic/technic/issues/163
https://github.com/minetest-technic/technic/pull/159
maybe [#100 by this comment](https://github.com/minetest-technic/technic/pull/100#issuecomment-55533537)

**Comment by ShadowNinja** [comment]
This results in checking the same node ten times, which is way too much, it also seems odd that this would increase accuracy.

**Comment by VanessaE** [comment]
This doesn't appear to be desired.  Sorry, @HybridDog

**Comment by HybridDog** [comment]
Sorry, github shows references again after rebasing.

**Pull request closed without merging**
