### PR TITLE
Fix item drop when digging mv furnace with upgrade

### PR DESCRIPTION
**Pull request by tenplus1**
Fixed crash when digging mv furnace containing upgrade

### CODE REVIEW

**Comment by Ekdohibs** [comment]
:+1:

**Comment by Ekdohibs** [comment]
Note: this and #271 fix the same bug in a different way: this one drops the items (which looks like what was intended), while the other forbids digging the machine. The question now is: which one do we want to merge?

**Comment by numberZero** [comment]
In my opinion, items should be dropped (as when digging node breaker, for example: it drops the tool contained, if any). Moreover, I think it should be applied to chests too. But as some players won’t agree with me, it can be made configurable.

**Comment by tenplus1** [comment]
Definitely drop upgrades within, this will fix machines from crashing for now and additional settings can be added at a later date.

**Comment by Ekdohibs** [comment]
https://github.com/minetest-technic/technic/commit/322615542e570f6363c7006b90f334e9ffd722c8

**Pull request closed without merging**
